### PR TITLE
Magic attribute & Apotheosis loot category

### PR DESCRIPTION
**Pull request by SiverDX**
Finished unless bugs pop up (seemed to work fine for now)

Idea for the compat handler from here: https://github.com/iron431/Irons-Spells-n-Spellbooks/blob/1.19.2/src/main/java/io/redspace/ironsspellbooks/compat/CompatHandler.java#L3

another attribute could be cooldown for wands
both attributes would be then applicable apotheosis affixes

dont know if and how much these attributes should apply to chants etc, don't really know anything about those

### CODE REVIEW

**Comment by SiverDX** [comment]
Regarding the structure of the compat handler (and the extra boolean):
- if something happens withing the runnable (exception or w/e) you could set the mod loaded flag to false (even though the mod is present), therefor disabling the faulty compat
- you could introduce a non-forge config (since forge config is not loaded early enough i think) to handle mod compat (enabling / disabling it), also utilizing the custom flag (this could also be done with a centralized ModList check I guess)

**Comment by SiverDX** [comment]
Regarding attribute compat with other mods (e. g. Iron's Spells 'n Spellbooks / Ars Nouveau) there are different things one can do
1. ignore their attributes
2. add the attributes together (addition) with a config to determine % (0 to 100) of the attribute value of the other mod to take / apply
3. decide which attribute to use (disable eidolons to instead only use Ars Nouveau)

personally leaning to 2.

**Comment by SiverDX** [comment]
Another question is if the magical knowledge attribute should also increase the duration of effects of the spells
I think it would fit (meaning it would act as a general magic multiplier, not just a damage multiplier)

**Comment by SiverDX** [comment]
Thing that could be added to this:
- Config to specify % of attribute usage of mod compatibility (0 to 100) (e.g. 75% for irons spellbooks -> only 75% of that attribute value is used)
- Cooldown affix
- Tag for tracking blacklist / additions
- Make the additional projectils bypass invulnerability (set flag and use flag for the damage source)

**Comment by SiverDX** [comment]
woops³ not planned for now
not a balancing person so you'd have to look at the numbers and if things should be split between different attributes

**Comment by Alexthw46** [comment]
Still haven't got the time to look well into this, from a quick look the PR changes are:

(I don't know Apoth too much but at least i know what affix and gems are)
- Two affixes for the wands, 
    - one that makes the projectiles homing (does this add the feature to the angel ring too?
    - one that makes more projectiles
- A magic power attribute, with relative boosting gem

I'm not opposed to affixes since that mod is crazy anyway on its own, would probably allow to still have fun with the wands.

For the magic attribute i'm not sure if it fits, the mod relies on the vanilla isMagic attribute of damage types to boost or reduce magic damage, and spells are meant to scale on devotion but the system is too young to decide how to handle it. So having an attribute that would only boost specific things and is only present when an unrelated mod is weird and might confuse on what the mod defines for magic.

Now, vanilla isMagic flag of 1.19 is not used by Ars without Scalaes addon nor Iron's Spells, but in 1.20 we can have a tag convention for magic that doesn't trigger witches's high resistance and will be adopted by Ars soon and already is by Apho (can file a suggestion on Irons for that).
It will still work for mods like Hexerei and Lodestone family (Malum basically) as they follow the same logic for magic damage.

I'd be more inclined to convert Warlock Hat's boost into an attribute modifier and use the attribute for all magic marked (1.19 by flag, 1.20 by tag)  than to hook into mods that have their own spell damage (which can be still bridge by a small addon). Will need to think and playtest this for a bit.

**Comment by SiverDX** [comment]
- No gem at the moment, just the attribute (which gets added to the wand when you lootify it with Apotheosis)
- Angel ring target mode is currently not used

The attribute itself is always present, meaning items / anything which boost any/all stats would affect it and also allows modpack makers to utilize it

Though the main reason for its addition is Apotheosis / a heavily modded environment since the wands are useless without any damage modifier like that

The usage of Irons attribute is mainly to allow for some small "it works together" kind of thing, where raw spell damage additions will boost magical damage of Eidolon as well since in a magical world where things work together by default that would be the case

**Comment by SiverDX** [comment]
i guess this is what you get when you try rebase for the first time

**Comment by Alexthw46** [comment]
w the heck, github merging ate a the changes to Attribute instead of committing them

**Pull request merged**
