### PR TITLE
Add turn-based crucible crafting

### PR DESCRIPTION
**Pull request by oitsjustjose**
This PR adds a new config option to enable Turn-Based crafting in the Crucible. By enabling this option, the crucible will ***never*** have its contents evaporate _unless_ there doesn't exist a recipe with the given amount of stirs and/or items. The original logic has been left entirely intact and this config option is left disabled by default.

This was added as without some way to view the recipe the player is actively trying to craft (ideally a map-like render of the recipe would show when the book is open and could be held in the off-hand, but that's a _lot_ of work), the player is left either having to take a screenshot and put it to the side (a privilege some don't have if you don't have a lot of screen real-estate) or are left to rely on memory.

As Ellpeck mentioned on stream today, the current implementation also _heavily_ depends on the player's speed and inventory management proficiency. This isn't something you can rely on, and adjusting `crucibleStepDuration` also makes it so the output takes `crucibleStepDuration`/2 to craft, so setting it to 1200 ticks isn't a particularly good solution from a player experience & design perspective.

Util methods were made in order to prevent an unreadable mess of nested for-loops, hope that's ok. This is the method I've always preferred as far as handling somewhat complicated logic.

Changes to `Registry.java` were just to make the project compile, though I'm unsure if this was here for a reason.

Thanks!!

### CODE REVIEW

**Comment by Alexthw46** [comment]
I only added a little backoff to not make it become a lag machine with no benefit as the crucible would try to instantly take the items or the stirs once the initial timer expired.

(At least from what i could test) While it can help a little in the current state between steps, as the second looping timer can let you adjust a bit better, it's far from allowing you to check how many stirs you need after already dropping the items or stirring first and then drop items.

You should make sure that the current behavior is intended, simply having the recipe "onHold" can replace the old behavior as default as it's not really a game changer but not sure if it's what you wanted

**Comment by oitsjustjose** [comment]
I like these changes - thanks a ton for the feedback and help on this! I was considering a backoff as well, wasn't sure if that was going to be overkill but after testing it I really like it. And thanks for the code dedup - meant to do that but it totally slipped my mind.

**Comment by Alexthw46** [comment]
So, do you want do edit this further or later after public testing?

**Comment by oitsjustjose** [comment]
In my private testing this looks just fine - I'd say it's public time!

**Pull request merged**
